name: CICD

on:
  push:
    branches: [alex/docker]

jobs:
  deploy:
    runs-on: [mandalore-core]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Stop pm2
        run: pm2 delete all

      - name: Change to project directory
        run: cd && cd Mandalore

      - name: Git fetch
        run: git fetch

      - name: Checkout alex/docker
        run: git checkout alex/docker

      - name: Pull latest changes
        run: git pull origin alex/docker

      - name: Install dependencies (adjust as needed)
        run: npm install

      - name: run build
        run: npm run build

      - name: Run your project (adjust as needed)
        run: pm2 start dist/main.js
