name: CICD

on:
  push:
    branches: [alex/docker]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t deimoss/mandalore-image:latest .
      - name: Publish image to docker hub
        run: docker push deimoss/mandalore-image:latest

  deploy:
    needs: build
    runs-on: [mandalore-docker]
    steps:
      - name: Pull image from docker hub
        run: docker pull deimoss/mandalore-image:latest
      - name: Run docker container
        run: docker run -d -p 80:8080 --name deimoss/mandalore-image-container deimoss/mandalore-image:latest
